/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TypographyRouteImport } from './routes/typography'
import { Route as LogoDesignRouteImport } from './routes/logo-design'
import { Route as GraphicsIconsRouteImport } from './routes/graphics-icons'
import { Route as ColorPaletteRouteImport } from './routes/color-palette'
import { Route as IndexRouteImport } from './routes/index'

const TypographyRoute = TypographyRouteImport.update({
  id: '/typography',
  path: '/typography',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoDesignRoute = LogoDesignRouteImport.update({
  id: '/logo-design',
  path: '/logo-design',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphicsIconsRoute = GraphicsIconsRouteImport.update({
  id: '/graphics-icons',
  path: '/graphics-icons',
  getParentRoute: () => rootRouteImport,
} as any)
const ColorPaletteRoute = ColorPaletteRouteImport.update({
  id: '/color-palette',
  path: '/color-palette',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/color-palette': typeof ColorPaletteRoute
  '/graphics-icons': typeof GraphicsIconsRoute
  '/logo-design': typeof LogoDesignRoute
  '/typography': typeof TypographyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/color-palette': typeof ColorPaletteRoute
  '/graphics-icons': typeof GraphicsIconsRoute
  '/logo-design': typeof LogoDesignRoute
  '/typography': typeof TypographyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/color-palette': typeof ColorPaletteRoute
  '/graphics-icons': typeof GraphicsIconsRoute
  '/logo-design': typeof LogoDesignRoute
  '/typography': typeof TypographyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/color-palette'
    | '/graphics-icons'
    | '/logo-design'
    | '/typography'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/color-palette'
    | '/graphics-icons'
    | '/logo-design'
    | '/typography'
  id:
    | '__root__'
    | '/'
    | '/color-palette'
    | '/graphics-icons'
    | '/logo-design'
    | '/typography'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColorPaletteRoute: typeof ColorPaletteRoute
  GraphicsIconsRoute: typeof GraphicsIconsRoute
  LogoDesignRoute: typeof LogoDesignRoute
  TypographyRoute: typeof TypographyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/typography': {
      id: '/typography'
      path: '/typography'
      fullPath: '/typography'
      preLoaderRoute: typeof TypographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logo-design': {
      id: '/logo-design'
      path: '/logo-design'
      fullPath: '/logo-design'
      preLoaderRoute: typeof LogoDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphics-icons': {
      id: '/graphics-icons'
      path: '/graphics-icons'
      fullPath: '/graphics-icons'
      preLoaderRoute: typeof GraphicsIconsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/color-palette': {
      id: '/color-palette'
      path: '/color-palette'
      fullPath: '/color-palette'
      preLoaderRoute: typeof ColorPaletteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColorPaletteRoute: ColorPaletteRoute,
  GraphicsIconsRoute: GraphicsIconsRoute,
  LogoDesignRoute: LogoDesignRoute,
  TypographyRoute: TypographyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
