services:
  - type: web
    name: cozyspace-style-guide
    runtime: docker
    plan: free
    buildCommand: bun install && bun run build:full
    startCommand: bun server/dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health